var examples =
[
    [ "Пример", "d9/d86/_xD0_x9F_xD1_x80_xD0_xB8_xD0_xBC_xD0_xB5_xD1_x80-example.html", null ],
    [ "__construct", "de/de4/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_1_1__construct-example.html", null ],
    [ "__get", "d7/dd3/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_1_1__get-example.html", null ],
    [ "__set", "d0/d58/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_1_1__set-example.html", null ],
    [ "set_lang", "d0/d23/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_1_1set_lang-example.html", null ],
    [ "set_user", "df/dd1/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_1_1set_user-example.html", null ],
    [ "/home/victoria/Photo-Rigma-BiZ/www/include/work.php", "d4/dcc/_2home_2victoria_2Photo-Rigma-BiZ_2www_2include_2work_8php-example.html", null ],
    [ "validate_array", "dd/d2d/_0c_0cPhotoRigma_0c_0cClasses_0c_0cDatabase_1_1validate_array-example.html", null ],
    [ "sanitize_array", "d0/d3e/_0c_0cPhotoRigma_0c_0cClasses_0c_0cDatabase_1_1sanitize_array-example.html", null ],
    [ "__construct", "d0/d5b/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_CoreLogic_1_1__construct-example.html", null ],
    [ "__get", "d5/d67/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_CoreLogic_1_1__get-example.html", null ],
    [ "__set", "da/d07/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_CoreLogic_1_1__set-example.html", null ],
    [ "set_lang", "d0/d44/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_CoreLogic_1_1set_lang-example.html", null ],
    [ "set_user", "df/deb/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_CoreLogic_1_1set_user-example.html", null ],
    [ "/home/victoria/Photo-Rigma-BiZ/www/include/work_corelogic.php", "df/dac/_2home_2victoria_2Photo-Rigma-BiZ_2www_2include_2work_corelogic_8php-example.html", null ],
    [ "generate_photo_data", "d1/d17/_0c_0cPhotoRigma_0c_0cClasses_0c_0cDatabase_1_1generate_photo_data-example.html", null ],
    [ "__construct", "d7/d54/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_Image_1_1__construct-example.html", null ],
    [ "__get", "d3/df0/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_Image_1_1__get-example.html", null ],
    [ "__set", "d3/d3a/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_Image_1_1__set-example.html", null ],
    [ "calculate_thumbnail_size", "dc/d08/_0c_0cPhotoRigma_0c_0cClasses_0c_0cDatabase_1_1calculate_thumbnail_size-example.html", null ],
    [ "process_image_resize_gmagick", "dd/d14/_0c_0cPhotoRigma_0c_0cClasses_0c_0cDatabase_1_1process_image_resize_gmagick-example.html", null ],
    [ "process_image_resize_imagick", "d2/dc2/_0c_0cPhotoRigma_0c_0cClasses_0c_0cDatabase_1_1process_image_resize_imagick-example.html", null ],
    [ "process_image_resize_gd", "d1/dbc/_0c_0cPhotoRigma_0c_0cClasses_0c_0cDatabase_1_1process_image_resize_gd-example.html", null ],
    [ "__construct", "d1/d10/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_Security_1_1__construct-example.html", null ],
    [ "/home/victoria/Photo-Rigma-BiZ/www/include/work_template.php", "d5/d2e/_2home_2victoria_2Photo-Rigma-BiZ_2www_2include_2work_template_8php-example.html", null ],
    [ "__construct", "d6/d86/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_Template_1_1__construct-example.html", null ],
    [ "__get", "d9/d5a/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_Template_1_1__get-example.html", null ],
    [ "__set", "da/d1f/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_Template_1_1__set-example.html", null ],
    [ "set_lang", "d7/dc8/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_Template_1_1set_lang-example.html", null ],
    [ "set_user", "d7/d15/_0c_0cPhotoRigma_0c_0cClasses_0c_0cWork_Template_1_1set_user-example.html", null ]
];